#!/bin/bash
# CAUTION: Script is used for resetting the states of the skill to a fresh one so it can be deployed
# as a template.
#
#          skill-package/skill.json will be reset
#          .ask/ folder and content will be deleted
#          It will make a backup of the current ask-states and skill.json to ask-states-local.json and skill-local.json
cp .ask/ask-states.json ./ask-states-local.json
cp skill-package/skill.json skill-package/skill-local.json
rm -rf .ask
cp skill-package/skill-reset.json skill-package/skill.json

